spring:
  application:
    name: personal-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}/personal
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect


service:
  fast-api:
    url: ${FAST_API_APP}
  product-api:
    url: ${FAST_PRODUCT_APP}
  llm-api:
    url: ${LLM_API_URL}
    key: ${LLM_API_KEY}
server:
  port: 8080


